import Head from 'next/head'
import Image from 'next/image'
import { Button } from '@material-ui/core';

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1>TESTE</h1>
        <Button variant="contained" color="primary">
          Primary
        </Button>
      </main>


    </div>
  )
}
